/*
 * USAGE: scala Src2tex.scala ファイル
 * ファイルをTexのtableに変換
 */
object Src2tex {
  import scala.io.Source
  final def main(args: Array[String]): Unit = {
    val arg = if (args.length >= 1) args(0) else ""
    
    if (arg != "") {
      val s = Source.fromFile(arg)
      printHeader()
      s.getLines.foldLeft(1)((i, line) => {
	//println(line)
	print("%5d & \\verb".format(i))
	val sep = if (!line.contains("|")) "|"
	          else if (!line.contains("+")) "+"
	          else if (!line.contains("-")) "-"
	          else if (!line.contains("@")) "@"
	          else "!"
	println(s"${sep}${line}${sep} \\\\ [-3pt]")
	i + 1
      })
      printFooter()
    }
  }

  def printHeader(): Unit = {
    println("""% This file generated by Src2tex.scala
%
\begin{quote}
\begin{tabular}{r|l}""")
  }
  def printFooter(): Unit = {
    println("""\end{tabular}
\end{quote}
% End """)
  }
}
/* End of file (Src2tex.scala) */
